cmake_minimum_required(VERSION 3.24)


macro(setup_whisper_backend_defaults)
    option(GGML_VULKAN                        ON)
    option(GGML_CUDA                          OFF)
    option(GGML_METAL                         OFF)
    option(GGML_MUSA                          OFF)
    option(GGML_SYCL                          OFF)
    option(WHISPER_STANDALONE                 OFF)
    option(WHISPER_ALL_WARNINGS               ON)
    option(WHISPER_ALL_WARNINGS_3RD_PARTY     ON)
    option(WHISPER_FATAL_WARNINGS             OFF)
    option(WHISPER_USE_SYSTEM_GGML            OFF)
    option(WHISPER_SANITIZE_THREAD            OFF)
    option(WHISPER_SANITIZE_ADDRESS           OFF)
    option(WHISPER_SANITIZE_UNDEFINED         OFF)
    option(WHISPER_BUILD_TESTS                OFF)
    option(WHISPER_BUILD_EXAMPLES             ON)
    option(WHISPER_BUILD_SERVER               OFF)
    option(WHISPER_CURL                       OFF)
    option(WHISPER_SDL2                       OFF)
    option(WHISPER_FFMPEG                     OFF)
    option(WHISPER_COREML                     OFF)
    option(WHISPER_COREML_ALLOW_FALLBACK      OFF)
    option(WHISPER_OPENVINO                   OFF)
endmacro()


macro(setup_sherpa_onnx_backend_defaults)
    option(SHERPA_ONNX_ENABLE_PYTHON                              OFF)
    option(SHERPA_ONNX_ENABLE_TESTS                               OFF)
    option(SHERPA_ONNX_ENABLE_CHECK                               OFF)
    option(SHERPA_ONNX_ENABLE_PORTAUDIO                           OFF)
    option(SHERPA_ONNX_ENABLE_JNI                                 OFF)
    option(SHERPA_ONNX_ENABLE_C_API                               ON)
    option(SHERPA_ONNX_ENABLE_WEBSOCKET                           OFF)
    option(SHERPA_ONNX_ENABLE_GPU                                 ON)
    option(SHERPA_ONNX_ENABLE_DIRECTML                            OFF)
    option(SHERPA_ONNX_LINK_D3D                                   OFF)
    option(SHERPA_ONNX_ENABLE_WASM                                OFF)
    option(SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION            OFF)
    option(SHERPA_ONNX_ENABLE_WASM_TTS                            OFF)
    option(SHERPA_ONNX_ENABLE_WASM_ASR                            OFF)
    option(SHERPA_ONNX_ENABLE_WASM_KWS                            OFF)
    option(SHERPA_ONNX_ENABLE_WASM_VAD                            OFF)
    option(SHERPA_ONNX_ENABLE_WASM_VAD_ASR                        OFF)
    option(SHERPA_ONNX_ENABLE_WASM_NODEJS                         OFF)
    option(SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT             OFF)
    option(SHERPA_ONNX_ENABLE_BINARY                              OFF)
    option(SHERPA_ONNX_ENABLE_TTS                                 OFF)
    option(SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION                 OFF)
    option(SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE OFF)
    option(SHERPA_ONNX_ENABLE_SANITIZER                           OFF)
    option(SHERPA_ONNX_BUILD_C_API_EXAMPLES                       OFF)
    option(SHERPA_ONNX_ENABLE_RKNN                                OFF)
    option(SHERPA_ONNX_ENABLE_AXERA                               OFF)
    option(SHERPA_ONNX_ENABLE_AXCL                                OFF)
    option(SHERPA_ONNX_ENABLE_ASCEND_NPU                          OFF)
    option(SHERPA_ONNX_ENABLE_QNN                                 OFF)
    option(SHERPA_ONNX_ENABLE_SPACEMIT                            OFF)
endmacro()


macro(print_all_workspace_flags_and_vars)
    message(STATUS "--- Workspace Configuration (Begin) ---")
    message(STATUS "STTSERVER_FORCE_COLOURED_OUTPUT:         ${STTSERVER_FORCE_COLOURED_OUTPUT}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_ADDRESS:      ${STTSERVER_ENABLE_SANITIZER_ADDRESS}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_UNDEFINED:    ${STTSERVER_ENABLE_SANITIZER_UNDEFINED}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_MEMORY:       ${STTSERVER_ENABLE_SANITIZER_MEMORY}")
    message(STATUS "STTSERVER_ENABLE_LINK_TIME_OPTIMIZATION: ${STTSERVER_ENABLE_LINK_TIME_OPTIMIZATION}")
    message(STATUS "STTSERVER_ENABLE_TRACY_PROFILING:        ${STTSERVER_ENABLE_TRACY_PROFILING}")
    message(STATUS "STTSERVER_BUILD_BACKEND_WHISPER:         ${STTSERVER_BUILD_BACKEND_WHISPER}")
    message(STATUS "STTSERVER_BUILD_BACKEND_PARAKEET:        ${STTSERVER_BUILD_BACKEND_PARAKEET}")
    message(STATUS "STTSERVER_BUILD_BACKEND_SHERPA_ONNX:     ${STTSERVER_BUILD_BACKEND_SHERPA_ONNX}")
    message(STATUS "STTSERVER_BUILD_EXECUTABLE:              ${STTSERVER_BUILD_EXECUTABLE}")
    message(STATUS "STTSERVER_BUILD_TESTS:                   ${STTSERVER_BUILD_TESTS}")
    message(STATUS "STTSERVER_BUILD_BENCHMARKS:              ${STTSERVER_BUILD_BENCHMARKS}")
    message(STATUS "-------------------------------")

    if(STTSERVER_BUILD_BACKEND_WHISPER OR STTSERVER_BUILD_BACKEND_PARAKEET)
        message(STATUS "--- Whisper/Parakeet Active Flags ---")
        message(STATUS "GGML_VULKAN:                                            ${GGML_VULKAN}")
        message(STATUS "GGML_CUDA:                                              ${GGML_CUDA}")
        message(STATUS "GGML_METAL:                                             ${GGML_METAL}")
        message(STATUS "GGML_MUSA:                                              ${GGML_MUSA}")
        message(STATUS "GGML_SYCL:                                              ${GGML_SYCL}")
        message(STATUS "WHISPER_STANDALONE:                                     ${WHISPER_STANDALONE}")
        message(STATUS "WHISPER_ALL_WARNINGS:                                   ${WHISPER_ALL_WARNINGS}")
        message(STATUS "WHISPER_ALL_WARNINGS_3RD_PARTY:                         ${WHISPER_ALL_WARNINGS_3RD_PARTY}")
        message(STATUS "WHISPER_FATAL_WARNINGS:                                 ${WHISPER_FATAL_WARNINGS}")
        message(STATUS "WHISPER_USE_SYSTEM_GGML:                                ${WHISPER_USE_SYSTEM_GGML}")
        message(STATUS "WHISPER_SANITIZE_THREAD:                                ${WHISPER_SANITIZE_THREAD}")
        message(STATUS "WHISPER_SANITIZE_ADDRESS:                               ${WHISPER_SANITIZE_ADDRESS}")
        message(STATUS "WHISPER_SANITIZE_UNDEFINED:                             ${WHISPER_SANITIZE_UNDEFINED}")
        message(STATUS "WHISPER_BUILD_TESTS:                                    ${WHISPER_BUILD_TESTS}")
        message(STATUS "WHISPER_BUILD_EXAMPLES:                                 ${WHISPER_BUILD_EXAMPLES}")
        message(STATUS "WHISPER_BUILD_SERVER:                                   ${WHISPER_BUILD_SERVER}")
        message(STATUS "WHISPER_CURL:                                           ${WHISPER_CURL}")
        message(STATUS "WHISPER_SDL2:                                           ${WHISPER_SDL2}")
        message(STATUS "WHISPER_FFMPEG:                                         ${WHISPER_FFMPEG}")
        message(STATUS "WHISPER_COREML:                                         ${WHISPER_COREML}")
        message(STATUS "WHISPER_COREML_ALLOW_FALLBACK:                          ${WHISPER_COREML_ALLOW_FALLBACK}")
        message(STATUS "WHISPER_OPENVINO:                                       ${WHISPER_OPENVINO}")
    endif()

    if(STTSERVER_BUILD_BACKEND_SHERPA_ONNX)
        message(STATUS "--- Sherpa-ONNX Active Flags ---")
        message(STATUS "SHERPA_ONNX_ENABLE_PYTHON:                              ${SHERPA_ONNX_ENABLE_PYTHON}")
        message(STATUS "SHERPA_ONNX_ENABLE_TESTS:                               ${SHERPA_ONNX_ENABLE_TESTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_CHECK:                               ${SHERPA_ONNX_ENABLE_CHECK}")
        message(STATUS "SHERPA_ONNX_ENABLE_PORTAUDIO:                           ${SHERPA_ONNX_ENABLE_PORTAUDIO}")
        message(STATUS "SHERPA_ONNX_ENABLE_JNI:                                 ${SHERPA_ONNX_ENABLE_JNI}")
        message(STATUS "SHERPA_ONNX_ENABLE_C_API:                               ${SHERPA_ONNX_ENABLE_C_API}")
        message(STATUS "SHERPA_ONNX_ENABLE_WEBSOCKET:                           ${SHERPA_ONNX_ENABLE_WEBSOCKET}")
        message(STATUS "SHERPA_ONNX_ENABLE_GPU:                                 ${SHERPA_ONNX_ENABLE_GPU}")
        message(STATUS "SHERPA_ONNX_ENABLE_DIRECTML:                            ${SHERPA_ONNX_ENABLE_DIRECTML}")
        message(STATUS "SHERPA_ONNX_LINK_D3D:                                   ${SHERPA_ONNX_LINK_D3D}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM:                                ${SHERPA_ONNX_ENABLE_WASM}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION:            ${SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_TTS:                            ${SHERPA_ONNX_ENABLE_WASM_TTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_ASR:                            ${SHERPA_ONNX_ENABLE_WASM_ASR}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_KWS:                            ${SHERPA_ONNX_ENABLE_WASM_KWS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_VAD:                            ${SHERPA_ONNX_ENABLE_WASM_VAD}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_VAD_ASR:                        ${SHERPA_ONNX_ENABLE_WASM_VAD_ASR}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_NODEJS:                         ${SHERPA_ONNX_ENABLE_WASM_NODEJS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT:             ${SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT}")
        message(STATUS "SHERPA_ONNX_ENABLE_BINARY:                              ${SHERPA_ONNX_ENABLE_BINARY}")
        message(STATUS "SHERPA_ONNX_ENABLE_TTS:                                 ${SHERPA_ONNX_ENABLE_TTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION:                 ${SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION}")
        message(STATUS "SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE: ${SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE}")
        message(STATUS "SHERPA_ONNX_ENABLE_SANITIZER:                           ${SHERPA_ONNX_ENABLE_SANITIZER}")
        message(STATUS "SHERPA_ONNX_BUILD_C_API_EXAMPLES:                       ${SHERPA_ONNX_BUILD_C_API_EXAMPLES}")
        message(STATUS "SHERPA_ONNX_ENABLE_RKNN:                                ${SHERPA_ONNX_ENABLE_RKNN}")
        message(STATUS "SHERPA_ONNX_ENABLE_AXERA:                               ${SHERPA_ONNX_ENABLE_AXERA}")
        message(STATUS "SHERPA_ONNX_ENABLE_AXCL:                                ${SHERPA_ONNX_ENABLE_AXCL}")
        message(STATUS "SHERPA_ONNX_ENABLE_ASCEND_NPU:                          ${SHERPA_ONNX_ENABLE_ASCEND_NPU}")
        message(STATUS "SHERPA_ONNX_ENABLE_QNN:                                 ${SHERPA_ONNX_ENABLE_QNN}")
        message(STATUS "SHERPA_ONNX_ENABLE_SPACEMIT:                            ${SHERPA_ONNX_ENABLE_SPACEMIT}")
    endif()


    message(STATUS "--- Workspace Configuration ( End ) ---")
endmacro()