#ifndef __LLM_ASR_MODEL_UNIFIED_INTERFACE_LLM_BACKEND_USED_DEFINITION_HEADER__
#define __LLM_ASR_MODEL_UNIFIED_INTERFACE_LLM_BACKEND_USED_DEFINITION_HEADER__


enum class BackendType { WHISPER, PARAKEET, SHERPA_ONNX, BACKEND_MAX };


#endif /* __LLM_ASR_MODEL_UNIFIED_INTERFACE_LLM_BACKEND_USED_DEFINITION_HEADER__ */
