#ifndef __STTSERVER_API_EXTERN_C_DEFINITION_MACRO
#define __STTSERVER_API_EXTERN_C_DEFINITION_MACRO
#ifdef __cplusplus
#   define STTSERVER_EXTERNC extern "C"
#   define STTSERVER_EXTERNC_DECL_BEGIN STTSERVER_EXTERNC {
#   define STTSERVER_EXTERNC_DECL_END   }
#else
#   define STTSERVER_EXTERNC
#   define STTSERVER_EXTERNC_DECL_BEGIN
#   define STTSERVER_EXTERNC_DECL_END
#endif
#endif
