cmake_minimum_required(VERSION 3.24)


macro(set_default_flag VAR VAL)
    if(NOT DEFINED ${VAR})
        set(${VAR} ${VAL} CACHE BOOL "")
    endif()
endmacro()


# See Here how to set options from other projects (While still letting cmdline args overrule):
# https://stackoverflow.com/a/27360232
macro(setup_whisper_backend_defaults)
    set_default_flag(GGML_VULKAN                    ON)
    set_default_flag(GGML_CUDA                      OFF)
    set_default_flag(GGML_METAL                     OFF)
    set_default_flag(GGML_MUSA                      OFF)
    set_default_flag(GGML_SYCL                      OFF)
    set_default_flag(WHISPER_STANDALONE             OFF)
    set_default_flag(WHISPER_ALL_WARNINGS           ON)
    set_default_flag(WHISPER_ALL_WARNINGS_3RD_PARTY ON)
    set_default_flag(WHISPER_FATAL_WARNINGS         OFF)
    set_default_flag(WHISPER_USE_SYSTEM_GGML        OFF)
    set_default_flag(WHISPER_SANITIZE_THREAD        OFF)
    set_default_flag(WHISPER_SANITIZE_ADDRESS       OFF)
    set_default_flag(WHISPER_SANITIZE_UNDEFINED     OFF)
    set_default_flag(WHISPER_BUILD_TESTS            OFF)
    set_default_flag(WHISPER_BUILD_EXAMPLES         ON)
    set_default_flag(WHISPER_BUILD_SERVER           OFF)
    set_default_flag(WHISPER_CURL                   OFF)
    set_default_flag(WHISPER_SDL2                   OFF)
    set_default_flag(WHISPER_FFMPEG                 OFF)
    set_default_flag(WHISPER_COREML                 OFF)
    set_default_flag(WHISPER_COREML_ALLOW_FALLBACK  OFF)
    set_default_flag(WHISPER_OPENVINO               OFF)
endmacro()


macro(setup_sherpa_onnx_backend_defaults)
    set_default_flag(SHERPA_ONNX_ENABLE_PYTHON                              OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_TESTS                               OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_CHECK                               OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_PORTAUDIO                           OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_JNI                                 OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_C_API                               ON )
    set_default_flag(SHERPA_ONNX_ENABLE_WEBSOCKET                           OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_GPU                                 ON )
    set_default_flag(SHERPA_ONNX_ENABLE_DIRECTML                            OFF)
    set_default_flag(SHERPA_ONNX_LINK_D3D                                   OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM                                OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION            OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_TTS                            OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_ASR                            OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_KWS                            OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_VAD                            OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_VAD_ASR                        OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_NODEJS                         OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT             OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_BINARY                              OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_TTS                                 OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION                 OFF)
    set_default_flag(SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_SANITIZER                           OFF)
    set_default_flag(SHERPA_ONNX_BUILD_C_API_EXAMPLES                       OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_RKNN                                OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_AXERA                               OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_AXCL                                OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_ASCEND_NPU                          OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_QNN                                 OFF)
    set_default_flag(SHERPA_ONNX_ENABLE_SPACEMIT                            OFF)
endmacro()


macro(print_all_workspace_flags_and_vars)
    message(STATUS "--- Workspace Configuration (Begin) ---")
    message(STATUS "STTSERVER_FORCE_COLOURED_OUTPUT:             ${STTSERVER_FORCE_COLOURED_OUTPUT}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_ADDRESS:          ${STTSERVER_ENABLE_SANITIZER_ADDRESS}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_UNDEFINED:        ${STTSERVER_ENABLE_SANITIZER_UNDEFINED}")
    message(STATUS "STTSERVER_ENABLE_SANITIZER_MEMORY:           ${STTSERVER_ENABLE_SANITIZER_MEMORY}")
    message(STATUS "STTSERVER_ENABLE_LINK_TIME_OPTIMIZATION:     ${STTSERVER_ENABLE_LINK_TIME_OPTIMIZATION}")
    message(STATUS "STTSERVER_ENABLE_TRACY_PROFILING:            ${STTSERVER_ENABLE_TRACY_PROFILING}")
    message(STATUS "STTSERVER_BUILD_LIBRARY_BACKEND_WHISPER:     ${STTSERVER_BUILD_LIBRARY_BACKEND_WHISPER}")
    message(STATUS "STTSERVER_BUILD_LIBRARY_BACKEND_SHERPA_ONNX: ${STTSERVER_BUILD_LIBRARY_BACKEND_SHERPA_ONNX}")
    message(STATUS "STTSERVER_BUILD_LIBRARY:                     ${STTSERVER_BUILD_LIBRARY}")
    message(STATUS "STTSERVER_BUILD_TESTS:                       ${STTSERVER_BUILD_TESTS}")
    message(STATUS "STTSERVER_BUILD_BENCHMARKS:                  ${STTSERVER_BUILD_BENCHMARKS}")
    message(STATUS "---------------------------------------")

    if(STTSERVER_BUILD_LIBRARY_BACKEND_WHISPER)
        message(STATUS "---  Whisper/Parakeet Active Flags  ---")
        message(STATUS "GGML_VULKAN:                    ${GGML_VULKAN}")
        message(STATUS "GGML_CUDA:                      ${GGML_CUDA}")
        message(STATUS "GGML_METAL:                     ${GGML_METAL}")
        message(STATUS "GGML_MUSA:                      ${GGML_MUSA}")
        message(STATUS "GGML_SYCL:                      ${GGML_SYCL}")
        message(STATUS "WHISPER_STANDALONE:             ${WHISPER_STANDALONE}")
        message(STATUS "WHISPER_ALL_WARNINGS:           ${WHISPER_ALL_WARNINGS}")
        message(STATUS "WHISPER_ALL_WARNINGS_3RD_PARTY: ${WHISPER_ALL_WARNINGS_3RD_PARTY}")
        message(STATUS "WHISPER_FATAL_WARNINGS:         ${WHISPER_FATAL_WARNINGS}")
        message(STATUS "WHISPER_USE_SYSTEM_GGML:        ${WHISPER_USE_SYSTEM_GGML}")
        message(STATUS "WHISPER_SANITIZE_THREAD:        ${WHISPER_SANITIZE_THREAD}")
        message(STATUS "WHISPER_SANITIZE_ADDRESS:       ${WHISPER_SANITIZE_ADDRESS}")
        message(STATUS "WHISPER_SANITIZE_UNDEFINED:     ${WHISPER_SANITIZE_UNDEFINED}")
        message(STATUS "WHISPER_BUILD_TESTS:            ${WHISPER_BUILD_TESTS}")
        message(STATUS "WHISPER_BUILD_EXAMPLES:         ${WHISPER_BUILD_EXAMPLES}")
        message(STATUS "WHISPER_BUILD_SERVER:           ${WHISPER_BUILD_SERVER}")
        message(STATUS "WHISPER_CURL:                   ${WHISPER_CURL}")
        message(STATUS "WHISPER_SDL2:                   ${WHISPER_SDL2}")
        message(STATUS "WHISPER_FFMPEG:                 ${WHISPER_FFMPEG}")
        message(STATUS "WHISPER_COREML:                 ${WHISPER_COREML}")
        message(STATUS "WHISPER_COREML_ALLOW_FALLBACK:  ${WHISPER_COREML_ALLOW_FALLBACK}")
        message(STATUS "WHISPER_OPENVINO:               ${WHISPER_OPENVINO}")
        message(STATUS "---------------------------------------")
    endif()

    if(STTSERVER_BUILD_LIBRARY_BACKEND_SHERPA_ONNX)
        message(STATUS "--- Sherpa-ONNX Active Flags ---")
        message(STATUS "SHERPA_ONNX_ENABLE_PYTHON:                              ${SHERPA_ONNX_ENABLE_PYTHON}")
        message(STATUS "SHERPA_ONNX_ENABLE_TESTS:                               ${SHERPA_ONNX_ENABLE_TESTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_CHECK:                               ${SHERPA_ONNX_ENABLE_CHECK}")
        message(STATUS "SHERPA_ONNX_ENABLE_PORTAUDIO:                           ${SHERPA_ONNX_ENABLE_PORTAUDIO}")
        message(STATUS "SHERPA_ONNX_ENABLE_JNI:                                 ${SHERPA_ONNX_ENABLE_JNI}")
        message(STATUS "SHERPA_ONNX_ENABLE_C_API:                               ${SHERPA_ONNX_ENABLE_C_API}")
        message(STATUS "SHERPA_ONNX_ENABLE_WEBSOCKET:                           ${SHERPA_ONNX_ENABLE_WEBSOCKET}")
        message(STATUS "SHERPA_ONNX_ENABLE_GPU:                                 ${SHERPA_ONNX_ENABLE_GPU}")
        message(STATUS "SHERPA_ONNX_ENABLE_DIRECTML:                            ${SHERPA_ONNX_ENABLE_DIRECTML}")
        message(STATUS "SHERPA_ONNX_LINK_D3D:                                   ${SHERPA_ONNX_LINK_D3D}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM:                                ${SHERPA_ONNX_ENABLE_WASM}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION:            ${SHERPA_ONNX_ENABLE_WASM_SPEAKER_DIARIZATION}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_TTS:                            ${SHERPA_ONNX_ENABLE_WASM_TTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_ASR:                            ${SHERPA_ONNX_ENABLE_WASM_ASR}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_KWS:                            ${SHERPA_ONNX_ENABLE_WASM_KWS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_VAD:                            ${SHERPA_ONNX_ENABLE_WASM_VAD}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_VAD_ASR:                        ${SHERPA_ONNX_ENABLE_WASM_VAD_ASR}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_NODEJS:                         ${SHERPA_ONNX_ENABLE_WASM_NODEJS}")
        message(STATUS "SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT:             ${SHERPA_ONNX_ENABLE_WASM_SPEECH_ENHANCEMENT}")
        message(STATUS "SHERPA_ONNX_ENABLE_BINARY:                              ${SHERPA_ONNX_ENABLE_BINARY}")
        message(STATUS "SHERPA_ONNX_ENABLE_TTS:                                 ${SHERPA_ONNX_ENABLE_TTS}")
        message(STATUS "SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION:                 ${SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION}")
        message(STATUS "SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE: ${SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE}")
        message(STATUS "SHERPA_ONNX_ENABLE_SANITIZER:                           ${SHERPA_ONNX_ENABLE_SANITIZER}")
        message(STATUS "SHERPA_ONNX_BUILD_C_API_EXAMPLES:                       ${SHERPA_ONNX_BUILD_C_API_EXAMPLES}")
        message(STATUS "SHERPA_ONNX_ENABLE_RKNN:                                ${SHERPA_ONNX_ENABLE_RKNN}")
        message(STATUS "SHERPA_ONNX_ENABLE_AXERA:                               ${SHERPA_ONNX_ENABLE_AXERA}")
        message(STATUS "SHERPA_ONNX_ENABLE_AXCL:                                ${SHERPA_ONNX_ENABLE_AXCL}")
        message(STATUS "SHERPA_ONNX_ENABLE_ASCEND_NPU:                          ${SHERPA_ONNX_ENABLE_ASCEND_NPU}")
        message(STATUS "SHERPA_ONNX_ENABLE_QNN:                                 ${SHERPA_ONNX_ENABLE_QNN}")
        message(STATUS "SHERPA_ONNX_ENABLE_SPACEMIT:                            ${SHERPA_ONNX_ENABLE_SPACEMIT}")
        message(STATUS "---------------------------------------")
    endif()


    message(STATUS "--- Workspace Configuration ( End ) ---")
endmacro()